<?php

namespace App\Controller\Admin;

use App\Entity\Category;
use App\Form\QuestionType;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\CollectionField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TimeField;

class CategoryCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Category::class;
    }

    #[\Override]
    public function configureActions(Actions $actions): Actions
    {
        $actions
            ->add(Crud::PAGE_INDEX, Action::DETAIL)
        ;

        return parent::configureActions($actions); // TODO: Change the autogenerated stub
    }

    /**
     * @throws \Exception
     */
    #[\Override]
    public function configureFields(string $pageName): iterable
    {
        $id = IdField::new('id');
        $name = TextField::new('name');
        $created_by = TextField::new('created_by');
        $updated_by = TextField::new('updated_by');
        $number_of_questions = AssociationField::new('questions');
        $coll_question = CollectionField::new('questions')->setEntryType(QuestionType::class);

        $time_created_at = TimeField::new('created_at');
        $time_updated_at = TimeField::new('time_updated_at');

        if (Crud::PAGE_INDEX === $pageName) {
            return [$id, $name, $number_of_questions];
        } elseif (Crud::PAGE_DETAIL === $pageName) {
            return [$id, $name,  $coll_question, $created_by, $updated_by, $time_created_at, $time_updated_at];
        } elseif (Crud::PAGE_NEW === $pageName) {
            return [$name, $coll_question];
        } elseif (Crud::PAGE_EDIT === $pageName) {
            return [$name, $coll_question];
        } else {
            throw new \Exception('Invalid page: '.$pageName);
        }
    }
}
