<?php

namespace App\Controller\Admin;

use App\Entity\System;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\Filters;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\CollectionField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class SystemCrudController extends AbstractCrudController
{




    public static function getEntityFqcn(): string
    {
        return System::class;
    }


   public function configureFilters(Filters $filters): Filters
   {

       $filters->add('name');
       return parent::configureFilters($filters); // TODO: Change the autogenerated stub
   }

    public function configureFields(string $pageName): iterable
    {
        $id = IdField::new('id');
        $name = TextField::new('name');
        $coll_question = CollectionField::new('questions')->setEntryType('App\Command\Form\CategoryType');


        if (Crud::PAGE_INDEX === $pageName) {
            return [$id, $name];
        }
//        elseif(Crud::PAGE_DETAIL === $pageName) {
//            return [$username, $email, $groups, $enabled, $lastLogin, $roles ];
//        }
        elseif(Crud::PAGE_NEW === $pageName) {
            return [$name, $coll_question];
        }
//        elseif(Crud::PAGE_EDIT === $pageName) {
//            return [$title, $editor_description, $editor_instructions, $editor_preparations, $coll_questions, $coll_configuration ];
//        }




    }



}
